name: Integration test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  integration-test:
    runs-on: ubuntu-latest
    needs: []
    
    strategy:
      matrix: 
        data: [
          { suffix: "dev-azure-1",    url: "https://:PAT@dev.azure.com/vimaster/ScorecardGenerator/_git/TestService1" },
          { suffix: "dev-azure-2",    url: "https://:PAT@dev.azure.com/vimaster/ScorecardGenerator/_git/TestService2" },
          { suffix: "visualstudio-1", url: "https://vimaster.visualstudio.com/DefaultCollection/ScorecardGenerator/_git/TestService1" },
          { suffix: "visualstudio-2", url: "https://vimaster.visualstudio.com/DefaultCollection/ScorecardGenerator/_git/TestService2" },
        ]
        
    steps:
    - uses: actions/checkout@v3
      with:
        path: app
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'
        dotnet-quality: 'daily'
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: app

    - run: |
        URL=$(echo "${{ matrix.data.url }}" | sed "s/PAT/${{ secrets.AZURE_PAT }}/g")
        git clone $URL test-data
      
    - name: Run binary inside "test-data"
      run: ../app/ScorecardGenerator/bin/Release/net8.0/ScorecardGenerator --azure-pat ${{ secrets.AZURE_PAT }} --output-path wiki
      working-directory: test-data
      
    - uses: actions/upload-artifact@v3
      with:
        name: output-${{ matrix.data.suffix }}
        path: test-data/wiki/*
