name: Generate Scorecard for thangchung/magazine-website-akka

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
# build matrix
matrix:
  include:



jobs:
  build:
    strategy:
      matrix:
      - suffix: dev-azure-1
        url: https://:${{ secrets.AZURE_PAT }}@dev.azure.com/vimaster/ScorecardGenerator/_git/TestService1
      - suffix: dev-azure-2
        url: https://:${{ secrets.AZURE_PAT }}@dev.azure.com/vimaster/ScorecardGenerator/_git/TestService12
      - suffix: visualstudio-1
        url: https://vimaster.visualstudio.com/DefaultCollection/ScorecardGenerator/_git/TestService1
      - suffix: visualstudio-2
        url: https://vimaster.visualstudio.com/DefaultCollection/ScorecardGenerator/_git/TestService2
        
    runs-on: ubuntu-latest
    steps:
    # setup this repository
    - uses: actions/checkout@v2
      with:
        path: app
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: app

    - run: git clone ${{ matrix.url }} test-data
    
    - name: Run binary inside "test-data"
      run: ../app/bin/Release/net7.0/ScorecardGenerator --azure-pat ${{ secrets.AZURE_PAT }}
      working-directory: test-data
      
    - uses: actions/upload-artifact@v2
      with:
        name: result-${{ matrix.suffix }}.md
        path: test-data/result.md