name: Generate Scorecard for thangchung/magazine-website-akka

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    needs: []
    
    strategy:
      matrix: 
        data: [
          { suffix: "dev-azure-1",    url: "https://:PAT@dev.azure.com/vimaster/ScorecardGenerator/_git/TestService1" },
          { suffix: "dev-azure-2",    url: "https://:PAT@dev.azure.com/vimaster/ScorecardGenerator/_git/TestService12" },
          { suffix: "visualstudio-1", url: "https://vimaster.visualstudio.com/DefaultCollection/ScorecardGenerator/_git/TestService1" },
          { suffix: "visualstudio-2", url: "https://vimaster.visualstudio.com/DefaultCollection/ScorecardGenerator/_git/TestService2" },
        ]
        
    steps:
      # setup this repository
    - uses: actions/checkout@v2
      with:
        path: app
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: app

      # setup test data (replace "PAT"  in matrix.data.url with secrets.AZURE_PAT)
    - name: Clone test data
    - run: |
        URL=$(${{ matrix.data.url }} | sed "s/PAT/${{ secrets.AZURE_PAT }}/g")
        git clone $URL test-data
      
      # generate scorecard
    - name: Run binary inside "test-data"
      run: ../app/bin/Release/net7.0/ScorecardGenerator --azure-pat ${{ secrets.AZURE_PAT }}
      working-directory: test-data
      
      # upload result
    - uses: actions/upload-artifact@v2
      with:
        name: result-${{ matrix.data.suffix }}.md
        path: test-data/result.md