name: Generate Scorecard for thangchung/magazine-website-akka

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # setup this repository
    - uses: actions/checkout@v2
      with:
        path: app
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: app

    # setup testdata
    - uses: actions/checkout@v2
      with:
        repository: thangchung/magazine-website-akka
        path: test-data

    - name: Run binary inside "test-data"
      run: ../app/bin/Release/net7.0/ScorecardGenerator --azure-pat ${{ secrets.AZURE_PAT }}
      working-directory: test-data
      
    - uses: actions/upload-artifact@v2
      with:
        name: result.md
        path: test-data/result.md
      
    - name: Validate result.md
      run: |
        if [ $(wc -l < test-data/result.md) -lt 12 ]; then
          echo "result.md appears to be invalid (less than 12 lines)
          exit 1
        fi
      working-directory: test-data