name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  unit-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        
    runs-on: ${{ matrix.os }}
        
    steps:
    - uses: actions/checkout@v3
      with:
        path: app
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: app

    - name: Generate coverage report
      run: dotnet test --collect:"XPlat Code Coverage" --results-directory "test-results"
      working-directory: app

    - name: Move coverage report from GUID folder to test-results
      run: find test-results -name "coverage.cobertura.xml" -exec mv {} test-results \;
      working-directory: app

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: app/test-results/coverage.cobertura.xml
        fail_ci_if_error: true
      if: ${{ always() && matrix.os == 'ubuntu-latest' }}

    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: app/test-results
      if: ${{ always() }}